#ifndef GSMobiDef_h
#define GSMobiDef_h

enum GS_MOBI_TYPE
{
    GS_MOBI_MOBIPOCKET_BOOK = 0x0002,
    GS_MOBI_NEWS_MAGAZINE   = 0x0103,
};

enum GS_MOBI_LANGUAGE
{
    GS_MOBI_LANGUAGE_ZH = 0x0004,
    GS_MOBI_LANGUAGE_EN = 0x0009,
};

enum GS_MOBI_EXTH_TYPE
{
    GS_MOBI_EXTH_AUTHOR       = 0x0064,
    GS_MOBI_EXTH_DESCRIPTION  = 0x0067,
    GS_MOBI_EXTH_PUBLISH_DATE = 0x006A,
};

#endif /* GSMobiDef_h */
